Add querying and removal of test results.
Misha12/Inkluzitron pull request #47
Opened 2021-05-04 15:55 UTC by Khubajsn

1. ![obrazek](https://user-images.githubusercontent.com/297170/117030302-c237b200-acff-11eb-88e2-7f4b3f7b7c67.png)
2. `CommandExtensions.GetCommandFormat` has been updated to work properly with command groups.
3. Added `IEmbedMetadata` + `EmbedMetadataExtensions`, which allows for concealing metadata in embeds. This is needed when processing embed reactions/buttons, so that it's possible to determine which module is responsible for editing the embed, if any. The HelpPageEmbed and related classes have been updated to use IEmbedMetadata as well.

    The `embedBuilder.WithMetadata` extension method will serialize the metadata into a URL query string-like format (such as `_k=HelpEmbed&PageNumber=1&PageCount=10`) and store it in the embed, somehow. The following destination selection logic is used:
    
    1. If the embed has an author with an avatar URL, that avatar URL is edited so that it's fragment portion (starting with `#`) includes the metadata.
    2. If the embed has an image URL set, that URL is edited in the same manner.
    3. The metadata are stored into the embed's footer.
    
    Later on, the `Embed.TryParseMetadata` extension can be used to parse/recover the data. The same logic is used for their lookup.

4. Added an `Entity` subdirectory/namespace inside `Inkluzitron.Data`, so that the entity classes are kept separate from the not-so-simple `DataContext`.
5. Moved test-related modules into their own subdirectory/namespace.
6. Moved `Inkluzitron.Settings` to `Inkluzitron.Models.Settings`

2021-05-04 20:29 UTC, Misha12 requested changes

2021-05-04 20:29 UTC, Misha12 commented on src/Inkluzitron/Data/Entities/QuizResult.cs
> +
Ty prázdné řádky tu musí být?

2021-05-04 20:29 UTC, Misha12 commented on src/Inkluzitron/Models/Settings/BdsmTestOrgSettings.cs
> +            string GetRequiredConfig(string key)
Tahle metoda by se krásně dala napsat jako extension metoda nad typem IConfiguration `string GetRequiredValue(this IConfiguration configuration, string key);`

2021-05-04 20:29 UTC, Misha12 commented on src/Inkluzitron/Modules/BdsmTestOrg/BdsmModule.cs
> +                .Take(1)
```suggestion
                .FirstOrDefaultAsync();
```

2021-05-04 20:29 UTC, Misha12 commented on src/Inkluzitron/Modules/BdsmTestOrg/BdsmModule.cs
> +                .FirstOrDefaultAsync();
```suggestion
```

2021-05-04 20:29 UTC, Misha12 commented on src/Inkluzitron/Modules/BdsmTestOrg/BdsmModule.cs
> +            if (await DbContext.BdsmTestOrgQuizResults.AsAsyncEnumerable().AnyAsync(r => r.Link == testResultLink))
```suggestion
            if (await DbContext.BdsmTestOrgQuizResults.AsQueryable().AnyAsync(r => r.Link == testResultLink))
```

Pokud se nepletu, tak `.AsAsyncEnumerable` zařízne SQL dotaz, tudíž se SQL vyhodnotí, že se mají stáhnout všechna data.

2021-05-04 20:29 UTC, Misha12 commented on src/Inkluzitron/Contracts/IReactionHandler.cs
> +        Task<bool> Handle(IUserMessage message, IEmote reaction, IUser user, IUser botUser);
Zřejmě to bude na více místech, takto dám jako comment. 
Mohli bychom držet zavedený standard, který myslím, že má i samotnej .NET. A to, že asynchronní metody končí na Async. Takže tady by se to jmenovalo `HandleAsync`.

2021-05-05 07:00 UTC, Misha12 approved these changes

2021-05-05 07:51 UTC, Misha12 approved these changes

2021-05-05 15:52 UTC, janch32 approved these changes
Budu věřit Michalovi 😀

2021-05-05 22:58 UTC, merged