Hotfix testu + flip obrázků a úprava traits algoritmu
Misha12/Inkluzitron pull request #54
Opened 2021-05-17 23:14 UTC by janch32

* Opraven špatný název kategorie testu
* Otočení obrázku, pokud je mířený na autora
* Úprava algoritmu použití obrázků podle testů uživatelů

2021-05-17 23:19 UTC, Khubajsn commented on src/Inkluzitron/Services/UserBdsmTraitsService.cs
> +        public double StrongTraitThreshold => Settings.StrongTraitThreshold;
to sis teda pomohl 😄

2021-05-17 23:20 UTC, Khubajsn requested changes

2021-05-17 23:20 UTC, Khubajsn commented on src/Inkluzitron/Services/UserBdsmTraitsService.cs
> +                .AsAsyncEnumerable()
AsAsyncQueryable

2021-05-17 23:23 UTC, janch32 commented on src/Inkluzitron/Services/UserBdsmTraitsService.cs
> +        public double StrongTraitThreshold => Settings.StrongTraitThreshold;
Zpřístupnil jsem to zvenku

2021-05-17 23:24 UTC, janch32 commented on src/Inkluzitron/Services/UserBdsmTraitsService.cs
> +                .AsAsyncEnumerable()
Já věděl, že je na tom něco špatně

2021-05-17 23:27 UTC, janch32 commented on src/Inkluzitron/Services/UserBdsmTraitsService.cs
> +                .AsAsyncEnumerable()
`AsAsyncQueryable` není, ale `AsQueryable` vypadá, že funguje

2021-05-17 23:27 UTC, Khubajsn approved these changes
ok

2021-05-18 06:17 UTC, theleteron approved these changes

2021-05-18 06:18 UTC, merged